/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CreateExpensesRouteImport } from './routes/create-expenses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'

const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExpensesRoute = CreateExpensesRouteImport.update({
  id: '/create-expenses',
  path: '/create-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/create-expenses': typeof CreateExpensesRoute
  '/expenses': typeof ExpensesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/create-expenses': typeof CreateExpensesRoute
  '/expenses': typeof ExpensesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/create-expenses': typeof CreateExpensesRoute
  '/expenses': typeof ExpensesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/create-expenses' | '/expenses' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/create-expenses' | '/expenses' | '/'
  id:
    | '__root__'
    | '/about'
    | '/create-expenses'
    | '/expenses'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  CreateExpensesRoute: typeof CreateExpensesRoute
  ExpensesRoute: typeof ExpensesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-expenses': {
      id: '/create-expenses'
      path: '/create-expenses'
      fullPath: '/create-expenses'
      preLoaderRoute: typeof CreateExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  CreateExpensesRoute: CreateExpensesRoute,
  ExpensesRoute: ExpensesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
